# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: I miei animali
email: your-email@domain.com
description:  Questa è la mia raccolta di animali! Qui ho raccolto le informazioni principali degli animali che mi
              incuriosiscono di più.
baseurl: "/animals" # the subpath of your site, e.g. /blog
url: "http://ddmng.github.io/animals" # the base hostname & protocol for your site
twitter_username: no
github_username:  ddmng

# Build settings
markdown: kramdown
